const:
  default-page-size: 20

file:
  directory: D:\pjh\GreenGramVer3\greengramver3

jwt:
  issuer: green@green.kr
  secret-key: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFightingD23sdfsdf23FDSADFSDFDass502RoomForJavaSprinass502RoomForJavaSprin


mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer2
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
  jackson:
    default-property-inclusion: non_null #클라이언트에 보내는 응답 JSON 을 만들때 NULL 인 속성은 제외하는 설정
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true



